### ISSUE TITLE
Process output step failing

### ISSUE THREAD

**Issue by kf-cuanschutz** [swanss/FragFold#3]
Hi I am unable to run the process output step please see my output below:

```
Loading data with 4 workers
Processing results...
gene_name: CDC11
condition: 30aa_monomer_CDC11
Traceback (most recent call last):
  File "/projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py", line 208, in <module>
    main(args)
  File "/projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py", line 159, in main
    confidence_df = get_confidence_dataframe(path,n_workers)
  File "/projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py", line 68, in get_confidence_dataframe
    raise ValueError(f"Unable to find colabfold output in the directory: {glob_path}")
ValueError: Unable to find colabfold output in the directory: /projects/kefo9343/FragFold/FragFold_pipeline/locallabfold/localcolabfold/data/*/output/log.txt
ERROR conda.cli.main_run:execute(47): `conda run python /projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py --import_json cdc11_output.json --experimental_data /projects/kefo9343/FragFold/FragFold/input/data/Savinov_2022_inhib_peptide_mapping.csv` failed. (See above for error)
Elapsed: 0hrs 0min 6sec
```

Here is my JSON file:

```
{
    "CDC11":
        {
        "30aa_monomer_CDC11": 
            {
            "colabfold":"/projects/kefo9343/FragFold/FragFold_pipeline/locallabfold/localcolabfold"
            }
        }
}
```

What should I do?

**Comment by swanss** [comment]
Hi! Looks like you passed the path to your colabfold installation. Please try replacing that with the path to your colabfold output, e.g. the directory where you ran colabfold, which should have another directory within titled `data` with the output from each colabfold job in it

**Comment by kf-cuanschutz** [comment]
Hi, thank you for the update! I did as you said and I got the following error.
Are you familiar with that kind of error?

```
Loading JSON file specifying where colabfold results are located: cdc11_output.json
Loading data with 4 workers
Processing results...
gene_name: CDC11
condition: 30aa_monomer_CDC11
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/projects/kefo9343/software/anaconda/envs/fragfold/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/projects/kefo9343/software/anaconda/envs/fragfold/lib/python3.7/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py", line 28, in load_confidence_data
    start,end = int(start),int(end)
ValueError: invalid literal for int() with base 10: 'colabfold'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py", line 208, in <module>
    main(args)
  File "/projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py", line 159, in main
    confidence_df = get_confidence_dataframe(path,n_workers)
  File "/projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py", line 72, in get_confidence_dataframe
    data = pool.map(func=load_confidence_data,iterable=all_paths,chunksize=1)
  File "/projects/kefo9343/software/anaconda/envs/fragfold/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/projects/kefo9343/software/anaconda/envs/fragfold/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: invalid literal for int() with base 10: 'colabfold'
ERROR conda.cli.main_run:execute(49): `conda run python /projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py --import_json cdc11_output.json --experimental_data /projects/kefo9343/FragFold/FragFold/input/data/Savinov_2022_inhib_peptide_mapping.csv` failed. (See above for error)
Elapsed: 0hrs 0min 4sec
[kefo9343@c3cpu-a2-u32-1 FragFold]$ vim /projects/kefo9343/FragFold/FragFold/input/data/Savinov_2022_inhib_peptide_mapping.csv
```

**Comment by kf-cuanschutz** [comment]
Hi,

When running process_output on the example I get the following error.
Do you know what that means?

`
Loading data with 4 workers
Traceback (most recent call last):
  File "/projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py", line 208, in <module>
    main(args)
  File "/projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py", line 145, in main
    colab_results = json.loads(file.read())
  File "/projects/kefo9343/software/anaconda/envs/fragfold/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/projects/kefo9343/software/anaconda/envs/fragfold/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/projects/kefo9343/software/anaconda/envs/fragfold/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 33 (char 34)
ERROR conda.cli.main_run:execute(49): `conda run python /projects/kefo9343/FragFold/FragFold/fragfold/colabfold_process_output.py --import_json colabfold_output_ftsz.json --experimental_data /projects/kefo9343/FragFold/FragFold/input/data/Savinov_2022_inhib_peptide_mapping.csv` failed. (See above for error)
Elapsed: 0hrs 0min 8sec
   
`
